[feat]reissue,로그아웃,닉네임중복검사 API호출, 위치정보 error시 default지역으로 설정 및 alert 띄우기
DutchiePay/DutchiePay-Front pull request #24
Opened 2024-10-01 03:51 UTC by ParkYongHo1

# Pull Request 🙇🏻‍♀️

## PR 타입 (하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 디자인

## 반영 브랜치
ex) feat/password-change -> main

## 변경 사항
reissue,로그아웃,닉네임중복검사 API호출, 위치정보 error시 default지역으로 설정 및 alert 띄우기구현했습니다.

## 테스트 결과
### reissue API 

#### hooks폴더 생성 후 커스텀훅(useReissueToken) api호출했습니다 
* UI변경 없는것은 컴포넌트 보단 커스텀훅이 더 좋다고해서 커스텀훅으로 작성했습니다.
![image](https://github.com/user-attachments/assets/1c5eb72d-613d-49f0-9b20-e98ec05abd94)
![image](https://github.com/user-attachments/assets/c46227eb-a54e-4646-8cd7-742ca1b21f9f)
분기 처리 해야 할 것
1. refresh토큰 만료
2. 비정상적인 접근
2가지 경우 로그아웃 진행해야할듯 합니다. 확정나면 기능 구현하겠습니다.

### 닉네임 중복검사 API
![image](https://github.com/user-attachments/assets/ba159ab0-1365-4fc7-b33d-0e8b91fdc9b0)
현재 onBlur이벤트로 처리했습니다.

### 위치정보 error시 처리
![image](https://github.com/user-attachments/assets/9ffeabaa-08ab-4c5a-8b4c-94862128c36c)

## ETC
추가적으로 적을 내용이 있으면 적어주세요. (선택)

2024-10-01 04:05 UTC, hyunjihub requested changes

2024-10-01 04:05 UTC, hyunjihub commented on dutchiepay/src/app/_components/_user/ResetSubmit.jsx
> +    reValidateMode: 'onBlur',
onBlur : 다른 input으로 이동되어야 함. onTouch : 포커스 잃을 때 전부
Blur로 하면 마지막 요소 유효성 검사가 잘 진행되지 않아서 Touched로 통일하는 게 좋을 것 같습니다

2024-10-01 04:05 UTC, hyunjihub commented on dutchiepay/src/app/_components/_user/ResetSubmit.jsx
> +        router.push('/');
로그아웃 구현된 걸로 알고 있습니다!

2024-10-01 04:09 UTC, hyunjihub commented on dutchiepay/src/redux/slice/loginSlice.js
>      },
setLocation 이렇게 말고 profile/nickname/location 하나로 합쳐도 각각 수정되도록 구현 가능합니다! 하나로 합쳐주세요! access는 사용이 다르기 때문에 따로 두는 게 좋을 것 같긴 합니다.

2024-10-02 04:57 UTC, ParkYongHo1 commented on dutchiepay/src/app/_components/_user/NicknameInput.jsx
> +            onBlur: checkNicknameAvailability,
onTouch 이건 input의 기본 이벤트 속성이 아니라서 작동을 안하더라구여

2024-10-02 05:29 UTC, hyunjihub commented
🥳

2024-10-02 05:29 UTC, hyunjihub approved these changes
👍🏻

2024-10-02 05:29 UTC, merged