[feat] 회원 비밀번호 재설정 시 현재 비밀번호 추가, 이메일,닉네임 중복검사, 전화번호 필수로 입력하게 구현
DutchiePay/DutchiePay-Front pull request #29
Opened 2024-10-06 14:56 UTC by ParkYongHo1

# Pull Request 🙇🏻‍♀️

## PR 타입 (하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 디자인

## 반영 브랜치
ex) feat/user-system -> main

## 변경 사항
회원 비밀번호 재설정 시 현재 비밀번호 추가, 이메일,닉네임 중복검사, 전화번호 필수로 입력하게 구현했습니다.

## 테스트 결과

### 이메일,닉네임 중복검사
![중복 api](https://github.com/user-attachments/assets/ee110f60-069d-4bcf-95d6-de801873815f)

### 현재 비밀번호 인풋 추가
![현재비밀번호](https://github.com/user-attachments/assets/bb126c8b-129a-4459-b847-a0c2c2fedccd)

### 전화번호 필수로 입력 
![image](https://github.com/user-attachments/assets/469fdc4d-9bfe-40eb-a10b-7b1a5cf91145)

## ETC
1. 현재 회원가입 시 touchedFields 때문에 실시간으로 처리하는데 중복 API호출은 onBlur이라 input에서 포커스 해제시 호출해서 논리적으로 이상합니다... 다른 방법 찾아보겠습니다 !

2, 현재 비밀번호 input 유효성 검사를 어떻게 해야 할 지 모르겠습니다.. 저희 쪽에서 현재 password정보를 불러올 방법을 찾아야,, 실시간 유효성 검사가 가능할듯한데 잘 모르겠어요..
![image](https://github.com/user-attachments/assets/16f29abd-39a4-481f-bc15-9e6fb0b4811c)

3. 이메일 컴포넌트를 비밀번호 재설정(find페이지)랑 회원가입 페이지에서 동시에 사용함으로 isFind 변수를 추가해줬습니다.
![image](https://github.com/user-attachments/assets/04b14f0b-73bc-4c28-9705-8ece4c9d41d5)

2024-10-06 16:00 UTC, hyunjihub commented
일단 코드 리뷰는 내일 하겠습니다! 현재 비밀번호 유효성은 무조건 비밀번호 형식만 체크해야 할 것 같습니다. 결국 현재 비밀번호를 입력하는 이유가 비밀번호를 알고있느냐인데 옳다 그르다를 실시간으로 확인할 수 있는 수단을 줘서는 안 될 것 같아요

2024-10-06 16:40 UTC, hyunjihub commented
회원가입 border의 유효성 성공 조건을 굳이 touched랑 error로 하지 않고 error가 없으면서 api도 성공일 때로 하면 되지 않을까 싶습니다. 실패 조건은 기존과 동일하게 하면 될 것 같어요

2024-10-07 02:29 UTC, hyunjihub requested changes

2024-10-07 02:29 UTC, hyunjihub commented on dutchiepay/src/app/_components/_user/EmailInput.jsx
> +  };
comment에서 남겼듯이 오류 발생 시 error를 true로 하는 게 아닌 success를 true로 하는 방식을 사용하면 이슈가 없을 것 같습니다. 또한 유효성 테스트는 pattern에서 진행하고 있기 때문에 유효성 테스트를 진행하면 의미가 없을 것 같습니다. trigger를 이용해서 pattern이 통과되었을 때 이메일 유효성을 진행하도록 설정하면 될 것 같습니다.

2024-10-07 02:29 UTC, hyunjihub commented on dutchiepay/src/app/_components/_user/ResetSubmit.jsx
> +        } else {
error.response는 필요한 조건이 아닌 것 같고 error.response.status랑 message도 같이 오기 때문에 message가 일치하는 것들로 해야 할 것 같습니다. 400으로 오는 에러가 항상 기존 비밀번호가 동일해서라고 확신할 수가 없기 때문에 message로 하는 게 조금 더 명확할 것 같아요!

2024-10-07 04:55 UTC, ParkYongHo1 commented on dutchiepay/src/app/_components/_user/EmailInput.jsx
> +  };
comment에서 남겼듯이 오류 발생 시 error를 true로 하는 게 아닌 success를 true로 하는 방식을 사용하면 이슈가 없을 것 같습니다. 이 부분 try문에서 에러를 처리하라는 말씀이실까요 ??

2024-10-07 06:04 UTC, hyunjihub commented on dutchiepay/src/app/_components/_user/EmailInput.jsx
> +  };
지금 border의 처리가 error가 없고 값이 들어있을 때 true로 표시되고 있으니까 결국 유효성 체크에서는 문제가 없지만, API 호출했을 때 오류가 발생할 때 문제가 되는것이니까 아예 border의 처리를 error로 말고 따로 변수를 두어서 해당 값이 true일 때 처리하라는 의미입니다. 저 부분 코드를 의미하는 게 아닙니다

2024-10-07 11:08 UTC, merged