[fix] 변경 API 오류 시, 원래 값으로 수정 값 덮어씌우지 않는 오류 수정
DutchiePay/DutchiePay-Front pull request #42
Opened 2024-10-10 08:19 UTC by ParkYongHo1

# Pull Request 🙇🏻‍♀️

## PR 타입 (하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 기능 삭제
- [x] 버그 수정
- [ ] 디자인

## 반영 브랜치
ex) fix/user-system-info-> main

## 변경 사항
변경 API 중복 에러 뜰시  원래 값으로 수정 값 덮어씌우지 않는 오류 수정

## 테스트 결과
![image](https://github.com/user-attachments/assets/3c1aea76-aff8-4a77-945d-d04e2d7b6775)

**다시 클릭 시**

![image](https://github.com/user-attachments/assets/246df3e7-c070-4768-83c8-79f3ae2d768d)

## ETC
추가적으로 적을 내용이 있으면 적어주세요. (선택)

2024-10-10 10:14 UTC, hyunjihub requested changes

2024-10-10 10:14 UTC, hyunjihub commented on dutchiepay/src/app/(routes)/mypage/info/page.jsx
> +          const response2 = await axios.get(
response2는 변수명으로 적합하지 않는 것 같습니다!

2024-10-10 10:14 UTC, hyunjihub commented on dutchiepay/src/app/(routes)/mypage/info/page.jsx
>          break;
중복 닉네임으로 변경 시, alert가 뜨고 수정 모드에서 일반 모드로 변경되는 것 같은데 사용자 관점에서는 실패했을 때 수정 모드로 유지돼서 다른 닉네임으로 수정 요청하는 게 더 좋을 것 같습니다! 닉네임 중복이 계속되면 계속 변경 버튼을 눌러야 할 것 같아서요!

2024-10-12 02:46 UTC, hyunjihub requested changes

2024-10-12 02:46 UTC, hyunjihub commented on dutchiepay/src/app/(routes)/mypage/info/page.jsx
> +          }
response가 200이 아닐 경우 아래 내용이 실행되지 않아서 status===200을 쓰지 않아도 될 것 같습니다. 그리고 어차피 닉네임 중복이 실시간으로 알려주는 것이 아니기 때문에 굳이 닉네임 중복검사 API를 호출하지 않아도 될 것 같습니다. 닉네임 변경 API에서 중복 시 처리해도 똑같이 동작할 것이기 때문에 닉네임 중복 검사를 없애고 프로필 변경 API만으로 처리하면 될 것 같아요

2024-10-12 14:20 UTC, ParkYongHo1 commented on dutchiepay/src/app/(routes)/mypage/info/page.jsx
> +          }
닉네임 변경 API 호출시 닉네임 중복관련 에러메시지가 따로 없구 401로 넘어오는데 일단은 모든 에러시 처리해 두긴했습니다. 근데 벡엔드에서 에러메시지 추가하던지 저희쪽에서 닉네임 중복 api를 호출하던지 해야할듯합니다..

2024-10-13 04:35 UTC, hyunjihub requested changes

2024-10-13 04:35 UTC, hyunjihub commented on dutchiepay/src/app/(routes)/mypage/info/page.jsx
>          }
중복 닉일 경우 반환 에러메시지 백엔드분들께 확인해서 해당 메시지 반환될 때만 하도록 수정해주시면 될 것 같습니다

2024-10-13 06:14 UTC, hyunjihub approved these changes

2024-10-13 06:14 UTC, merged