[fix] 이미지 더보기 화살표 클릭시 이미지 더보기 아이콘도 같이 내려가는 에러 수정
DutchiePay/DutchiePay-Front pull request #69
Opened 2024-10-19 17:44 UTC by ParkYongHo1

# Pull Request 🙇🏻‍♀️

## PR 타입 (하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 기능 삭제
- [x] 버그 수정
- [ ] 디자인

## 반영 브랜치
ex) fix/images-more-icon-> main

## 변경 사항
이미지 더보기 화살표 클릭시 이미지 더보기 아이콘도 같이 내려가는 에러 수정

## 테스트 결과
![image](https://github.com/user-attachments/assets/339f9e09-5e21-445c-8cef-4bbae80ed31e)
## ETC
추가적으로 적을 내용이 있으면 적어주세요. (선택)

2024-10-21 07:55 UTC, hyunjihub requested changes

2024-10-21 07:55 UTC, hyunjihub commented on dutchiepay/src/app/_components/_commerce/ReviewItem.jsx
> +              layout="fill" // 부모 div의 크기를 채움
layout="fill"에서 layout이 deprecated된 걸로 알고 있습니다!

2024-10-21 07:55 UTC, hyunjihub commented on dutchiepay/src/app/_components/_commerce/ReviewItem.jsx
> +              objectFit="cover"
objectFit 또한 deprecated되고 style 속성으로 사용하도록 변경된 걸로 알고 있습니다!

2024-10-22 05:39 UTC, hyunjihub commented on dutchiepay/src/app/_components/_commerce/ReviewItem.jsx
> +  );
다른 Image 컴포넌트에서는 다 인라인으로 두어서 useMemo로 사용하게 되면 다른 코드들도 다 바뀌어야 할 것 같은데 혹시 useMemo로 스타일 적용하는 이유가 있을까요?

2024-10-22 06:26 UTC, ParkYongHo1 commented on dutchiepay/src/app/_components/_commerce/ReviewItem.jsx
> +  );
inline으로 스타일 줄경우 style={{object:'cover'}} 새로운 객체가 매번 생성돼서 아마 재렌더링이 발생해서 성능상 좋지 않을겁니다. 그래서 useMemo로 한번만 렌더링 되게 구현했습니다.

2024-10-24 06:39 UTC, hyunjihub approved these changes

2024-10-24 06:39 UTC, merged