[feat] Pagination 구현
DutchiePay/DutchiePay-Front pull request #76
Opened 2024-10-27 05:21 UTC by ParkYongHo1

# Pull Request 🙇🏻‍♀️

## PR 타입 (하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 디자인

## 반영 브랜치
ex) feat/pagenation -> main

## 변경 사항
문의 페이지 네이션 구현

## 테스트 결과
### 등록된 문의가 없을 경우
![image](https://github.com/user-attachments/assets/ba0c7be5-385a-477b-abff-fffa63f1c59b)

### 등록된 문의가 있을 경우
![image](https://github.com/user-attachments/assets/93f3612c-e6fe-44c3-9b5c-f1ade9bad17b)

## ETC
현재 리뷰 페이지네이션는 API 아직 대끼가 잘 되지않아  API호출은 적용 안해두었습니다 API 나오면 바로 등록된 리뷰없을 시 컴포넌트와 API 적용해두겠습니다. 
![image](https://github.com/user-attachments/assets/15152517-47e3-402d-9040-4715981e6452)

2024-10-29 03:16 UTC, hyunjihub requested changes

2024-11-03 13:32 UTC, hyunjihub requested changes

2024-11-04 05:35 UTC, ParkYongHo1 commented on dutchiepay/src/app/_components/_commerce/ReviewItem.jsx
> +        <div className="w-[1000px]">
`<div className={`${hasImages ? 'max-w-[848px]' : 'max-w-[1000px]'}`}>`
이렇게 수정시 아래 이미지 처럼되어서
![image](https://github.com/user-attachments/assets/247fd119-c4ca-4cee-998a-1ac0044e5ddf)
`<div className={`${hasImages ? 'w-[848px]' : 'w-[1000px]'}`}>` 이렇게 처리했습니다

2024-11-04 06:32 UTC, hyunjihub approved these changes

2024-11-04 06:32 UTC, merged